#!/usr/bin/env node
/**
 * Generates preview/tokens.generated.css from tokens/two.css.
 *
 *   node tools/build-preview.mjs
 *
 * Why this exists: preview/index.html has no build step, so it cannot read a
 * Tailwind `@theme` block — browsers ignore unknown at-rules, and the custom
 * properties inside would never apply. This lifts them into a plain `:root`.
 *
 * It is generated rather than hand-copied so the preview can never drift from
 * the real tokens. CI should run this and fail on a dirty diff:
 *
 *   node tools/build-preview.mjs && git diff --exit-code preview/
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, '..', 'tokens', 'two.css');
const out = join(here, '..', 'preview', 'tokens.generated.css');

const css = readFileSync(src, 'utf8');

// Grab the @theme block, brace-matched so nested rules cannot truncate it.
const start = css.indexOf('@theme');
if (start === -1) throw new Error('no @theme block in tokens/two.css');
let depth = 0;
let end = -1;
for (let i = css.indexOf('{', start); i < css.length; i++) {
  if (css[i] === '{') depth++;
  else if (css[i] === '}' && --depth === 0) {
    end = i;
    break;
  }
}
const theme = css.slice(css.indexOf('{', start) + 1, end);

const decls = [...theme.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/gi)].map(
  ([, name, value]) => `  ${name}: ${value.trim().replace(/\s+/g, ' ')};`
);

if (!decls.length) throw new Error('no custom properties found in @theme');

writeFileSync(
  out,
  [
    '/* GENERATED by tools/build-preview.mjs from tokens/two.css. Do not edit. */',
    ':root {',
    ...decls,
    '}',
    '',
  ].join('\n')
);

console.log(`wrote ${decls.length} tokens to preview/tokens.generated.css`);
